# Generated by Django 2.2.17 on 2020-12-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=200)),
                ('ticket_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ارتباط با ما'), (2, 'دوره های آنلاین'), (3, 'سفارش پروژه')], default=1)),
                ('body', models.TextField()),
                ('checked', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
