"""
Django settings for ai_site project.

Generated by 'django-admin startproject' using Django 2.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.contrib.messages import constants as messages
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'isw9h$+ame7_6kb*=wg#*rtj)if3jy4$teq&&celk!4!89+)1*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.icc-aria.ir',
                 'icc-aria.ir', '127.0.0.1', 'localhost']


# Application definition
INSTALLED_APPS = [
    #'multi_captcha_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    'robots',
    "taggit",
    'snowpenguin.django.recaptcha2',
    "compressor",
    'crispy_forms',
    'imagekit',
    'ckeditor',
    'ckeditor_uploader',
    'meta',
    'blog',
    'website',
    'paginator',
    'google_analytics',

]

USE_DJANGO_JQUERY = True
#USE_DJANGO_JQUERY

# meta configurations
META_SITE_PROTOCOL = 'https'
META_SITE_DOMAIN = 'ray-i.com'
META_SITE_TYPE = "website"
META_USE_SITES = True
META_DEFAULT_KEYWORDS = ['python','ai','iot','py3','پایتون','ML','RL','machine learning','reinforcment learning','ماشین لرنینگ']
META_INCLUDE_KEYWORDS = ['python','ai','iot','py3','پایتون','ML','RL','machine learning','reinforcment learning','ماشین لرنینگ']
META_USE_OG_PROPERTIES = True
META_USE_TWITTER_PROPERTIES = True
META_USE_SCHEMAORG_PROPERTIES = True
META_USE_TITLE_TAG = True
META_SITE_NAME = "ray-i"
META_TWITTER_SITE = "https://ray-i.com"
META_DEFAULT_IMAGE = "/static/img/ai.png"
#META_FB_TYPES = True

META_FB_AUTHOR_URL = "https://ray-i.com"
META_TWITTER_SITE = "ray-i"
META_SCHEMAORG_TYPE = "WebSite"

# robots.txt configuration
ROBOTS_USE_SITEMAP = True
ROBOTS_USE_HOST = True




# ckeditor configuration
CKEDITOR_UPLOAD_PATH = 'ckeditor_uploads'
#CKEDITOR_BASEPATH = "/static/ckeditor"
CKEDITOR_CONFIGS = {
    'default': {
        'width': '100%',
        'toolbar': 'full',
        'extraPlugins': ','.join([
            'uploadimage',  # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'image2',
            # 'devtools',   
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'codesnippet',
        ]),
        
    },
    

}

# admin captcha config
MULTI_CAPTCHA_ADMIN = {
    #'engine': 'simple-captcha',
    'engine': 'recaptcha2_snow',
}
RECAPTCHA_PUBLIC_KEY = '#'
RECAPTCHA_PRIVATE_KEY = '#'


# crispy form config
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# sitemaps config
SITE_ID = 2

# middlewares configs
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Email Configurations
if not DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'mail.icc-aria.ir'
    EMAIL_PORT = 587
    EMAIL_HOST_USER = "info@icc-aria.ir"
    EMAIL_HOST_PASSWORD = ""
    EMAIL_USE_SSL = False
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = "info@icc-aria.ir"
else:
    # for local test usage
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST = 'localhost'
    EMAIL_PORT = 1025
    


# Root Url Configurations
ROOT_URLCONF = 'ai_site.urls'

# Templates Configurations
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Sync or Async service
WSGI_APPLICATION = 'ai_site.wsgi.application'

# DataBase Configs
if not DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'iccariai_icc_aria_db',
            'USER': 'iccariai_icc_aria',
            'PASSWORD': '',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Compress Configs
COMPRESS_ENABLED = True

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)


COMPRESS_CSS_FILTERS = [
    'compressor.filters.cssmin.CSSMinFilter'
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter'
]


# password validators alg
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# time and language conf
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# static and media Config
MEDIA_URL = '/media/'
STATIC_URL = '/static/'

if not DEBUG:
    STATICFILES_DIRS = [BASE_DIR+"/assets", ]
    STATIC_ROOT = '/home/iccariai/public_html/static'
    MEDIA_ROOT = '/home/iccariai/public_html/media'
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
    STATICFILES_DIRS = [os.path.join(
        BASE_DIR, 'static/'), os.path.join(BASE_DIR, 'media')]
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# messages
MESSAGE_TAGS = {
    messages.DEBUG: 'info',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

GOOGLE_ANALYTICS = {
    'google_analytics_id': '#',
}
